### PR TITLE
Refactor controller && add price definition for master option_type

### PR DESCRIPTION
**Pull request by kpitn**
Refactor controller to add method in model.

Add price definition for master option_type

### CODE REVIEW

**Comment by jsqu99** [comment]
Thanks for the submission.

I looked at the commit briefly, twice, and I'm still not 100% sure what it is doing.  I'm going to look more closely ASAP.

Thanks,

Jeff

**Comment by kpitn** [comment]
You could test like this :

Create an Spree option type (you can choose a price).
Create an Ad Hoc Option type on a product (The price is set automatically from your Spree Option Type) But you can still change the price if you want.

And refactor of the controller, it's more dry to have option_values creation in the model.
You just need to make :
@product.ad_hoc_option_types << AdHocOptionType.new(:option_type => OptionType.find(params[:id]))
to create option_values.

**Comment by jsqu99** [comment]
I think I love the idea of what you submitted, but did you test it?  Because I get:

ActionView::MissingTemplate in Admin/option_types#edit

Showing /home/jsquires/src/clones/spree/core/app/views/admin/option_types/edit.html.erb where line #26 raised:

Missing partial admin/option_types/option_value_price with {:handlers=>[:erb, :rjs, :builder, :rhtml, :rxml], :formats=>[:html], :locale=>[:en, :en]} in view paths "/home/jsquires/src/old_rails/flexi_060/app/views", "/home/jsquires/src/old_rails/flexi_060/app/views", "/home/jsquires/src/clones/spree_flexi_variants/app/views", "/home/jsquires/src/clones/spree/app/views", "/home/jsquires/src/clones/spree/sample/app/views", "/home/jsquires/src/clones/spree/promo/app/views", "/home/jsquires/src/clones/spree/dash/app/views", "/home/jsquires/src/clones/spree/api/app/views", "/home/jsquires/src/clones/spree/auth/app/views", "/home/jsquires/.rvm/gems/ruby-1.9.2-p180@rails3/gems/devise-1.3.3/app/views", "/home/jsquires/src/clones/spree/core/app/views"

Extracted source (around line #26):

23:     </tbody>
24: </table>
25: <span id="new_add_option_value">
26:     <%= link_to_add_fields t("add_option_value"), "tbody#option_values", f, :option_values %>
27:   </span>
28: 
29:   <%= render :partial => 'admin/shared/edit_resource_links' %>

**Comment by jsqu99** [comment]
Yeah, I think your pull request is missing the partial: admin/option_types/option_value_price.  Can you please commit & resubmit?

**Pull request merged**
