### PR TITLE
Spree 1 3 stable

### PR DESCRIPTION
**Pull request by vp993**
I'm updated this gem for spree-1-3-stable.

### CODE REVIEW

**Comment by jsqu99** [comment]
thank you for contributing.  I'm going to need some time to review this.  I'm a bit confused by what appears to be some application-specific text in some of the files.

Also, I'm getting a warning that the pull request can't be automatically merged.

**Comment by vp993** [comment]
Sorry, I delete this customization in text commit. This feature from branch spree-1-2-stable. Perhaps because of this was a mistake?

**Comment by jetsgit** [comment]
@Snuff,  just tried out the fork you made. Fixed issue in admin, but broke pretty much everything regarding displaying price, updating changes in variant, etc.

**Comment by vp993** [comment]
Hm.. It's works for me. Okay, Im try to fix it.

**Pull request closed without merging**
