### PR TITLE
Fix Javascript error on engraving calculator

### PR DESCRIPTION
**Pull request by charredUtensil**

### CODE REVIEW

**Comment by radar** [comment]
Could you please move the migration into another PR?

**Comment by charredUtensil** [comment]
How do I do that? I added that commit after creating this PR and didn't intend for it to appear here.

**Comment by radar** [comment]
@charredUtensil 

```
git reset --hard HEAD~1 # This will remove the commit from that branch
git push origin spree-2-1-wip --force # This will override that branch on GitHub and update the PR accordingly.
```

**Comment by charredUtensil** [comment]
Done. Thanks.

Is there a way to keep pushing updates without updating this pull request?

**Pull request closed without merging**
